### ISSUE TITLE
不好意思，微信打字不方便，没找到更好方式提问。。希望能解答下。谢谢！

### ISSUE THREAD

**Issue by live17909** [enbandari/HackRetrofit#1]
如果需要传字符数组，如何传呢？。。
params.put("pmId1[]\"; filename=\"ame\"", toRequestBody("pmId11"));
params.put("pmId1[]\"; filename=\"ame\"", toRequestBody("pmId12"));
params.put("pmId1[]\"; filename=\"ame\"", toRequestBody("pmId13"));
这种方式传好象服务器解析不了，？，求助，谢谢！

**Comment by live17909** [comment]
params.put("projectManager[]",  toRequestBody(pm1));
        params.put("projectManager[]",  toRequestBody(pm2));
        params.put("projectManager[]",  toRequestBody(pm3));

**Comment by live17909** [comment]
```
@Multipart
@POST("publicService.do?action=submitBriberyInvestigation&dataType=mobile&ecafeNotRedirect=true")
Observable<CommitResult> submitBriberyInvestigation(@Query("ecafeToken") String ecafeToken, @PartMap Map<String, RequestBody> map,
                                                    @PartMap Map<String, RequestBody[]> pmap);
```

//                                                        @PartMap Map<String, String[]> pMap);
//                                                 ,@PartMap Map<String, String[]> projectManagerId);

```
@POST("publicService.do?action=submitBriberyInvestigation&dataType=mobile&ecafeNotRedirect=true")
Observable<CommitResult> submitBriberyInvestigation(@Query("ecafeToken") String ecafeToken,@Body DocSurveyActivityFragment.DetailDto data);
```

试了都不行。。基本是服务端接收为空，要么就是解析不了

**Comment by bennyhuo** [comment]
时间有点儿久了我有点儿不太记得了，看你的意思是想要在一个参数当中提交一个 RequestBody数组？你确定下这个Retrofit能支持么？最近没有太多时间，暂时没空细看这块儿的源码了，建议你检查一下吧，看上去不是很复杂，就是用法问题。

**Comment by bennyhuo** [comment]
如果有问题可以发邮件联系我哈，也可以随时重新打开这个 issue ~我先关掉这个了
